name: Stale Issue and PR Management

on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  stale:
    runs-on: [ubuntu-latest, debian-dell]
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Mark and close stale items
        uses: actions/stale@v10
        with:
          stale-issue-message: >-
            This issue has had no activity for 45 days and is being marked stale.
            Add a comment or update to keep it open.
          close-issue-message: >-
            Closing due to inactivity. If this is still relevant, please open a new issue
            with updated reproduction details.
          stale-pr-message: >-
            This pull request has had no activity for 30 days and is being marked stale.
            Add a comment or push changes to keep it open.
          close-pr-message: >-
            Closing due to inactivity. You can reopen with an update when ready.
          days-before-issue-stale: 45
          days-before-issue-close: 14
          days-before-pr-stale: 30
          days-before-pr-close: 14
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: pinned,security,planned
          exempt-pr-labels: pinned,security,work-in-progress
          remove-issue-stale-when-updated: true
          remove-pr-stale-when-updated: true
          operations-per-run: 500

      - name: Lock inactive closed issues
        uses: dessant/lock-threads@v5
        with:
          issue-inactive-days: "30"
          issue-lock-reason: "resolved"
          process-only: "issues"
